name: run_times
description: Running app made by runners for runners.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  email_validator: ^3.0.0
  http: ^1.2.2
  font_awesome_flutter: ^10.4.0
  url_launcher: ^6.1.10
  flutter_dotenv: ^5.0.2
  http_parser: ^4.1.0
  lints: ^4.0.0
  shared_preferences: ^2.0.6
  oauth2_client: ^3.0.0
  logging:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  vm_service: ^14.2.4
  test_api: ^0.7.3
  string_scanner: ^1.3.0
  meta: ^1.15.0
  material_color_utilities: ^0.12.0
  leak_tracker_flutter_testing: ^3.0.5
  leak_tracker: ^10.0.5
  collection: ^1.19.0
  js: ^0.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
